name: getjob
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.7+8

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.1
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.0.2
  country_state_city_picker: ^1.2.8
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.6.0
  email_auth: ^2.0.0
  equatable: ^2.0.5
  file_picker: ^8.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_otp_text_field: ^1.1.3+2
  flutter_pdfview: ^1.3.2
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^ 0.5.1
  path: ^1.9.0
  path_provider: ^2.1.4
  searchfield: ^1.0.5
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^26.2.14

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/job-search.png

  android_12:
    image: assets/images/splash12.png
    icon_background_color: "#ffffff"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/job-search.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/job-search.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/job-search.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/images/job-search.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

